### PR TITLE
CustomSciptExtension1 did not complete when setting the password.

### PR DESCRIPTION
**Pull request by tsukashusan**
Solved the problem that PowerShell did not run when the password was set.

### CODE REVIEW

**Comment by paulopsgility** [comment]
@tsukashusan What issue is the PR proposing to fix? I just tested the deployment and it deployed normally. 

The password is in the script. When the script fails it is usually due to low memory conditions on the VM during the deployment. You can pass in the username and password but it would be the same as not passing it in so it wouldn't resolve a failure of the custom script extension.

**Comment by tsukashusan** [comment]
@paulopsgility -san,
The script below shows the default values set.

>configure-onprem-sql.ps1

And the default value is **always** used as the computer login password.

 `param($sourceFileUrl="..",  $user="demouser", $password="Demo@pass123")`

>azure-deploy.json

`"commandToExecute": "[concat('powershell -ExecutionPolicy Unrestricted -File ', variables('customScriptFolder'), '/', variables('customScriptUriScriptFileName'))]"`

>configure-onprem-sql.ps1

```
$spassword =  ConvertTo-SecureString "$password" -AsPlainText -Force
$credential = New-Object System.Management.Automation.PSCredential("$env:COMPUTERNAME\$user", $spassword)

Enable-PSRemoting -Force
Invoke-Command -Credential $credential -ComputerName $env:COMPUTERNAME -ArgumentList "Password", $spassword -ScriptBlock { 
```

However, the user can arbitrarily change the user ID and password with azure-deploy.json.
If the user changes to any user ID and password, the script(configure-onprem-sql.ps1) will stop working.
>azure-deploy.json

```
        "administratorLogin": {
            "type": "string",
            "defaultValue": "demouser" <-※
        },
        "administratorLoginPassword": {
            "type": "securestring",
            "defaultValue": "Demo@pass123"<-※
        },
...
        "adminUsername": {
            "type": "string",
            "defaultValue": "demouser"<-※
        },
        "adminPassword": {
            "type": "securestring",
            "defaultValue": "Demo@pass123"<-※
        },

    },
```

image

**Comment by paulopsgility** [comment]
@tsukashusan  So that is the way we used have it setup but we had to hard code it for reliability. It may work fine now but the lab is written for that username and password which means we would need to update the lab guide as well. We don't currently have this one scheduled for a test fix or update so I am going to mark this as an enhancement and we will get it on the next test fix/update

**Comment by tsukashusan** [comment]
@paulopsgility -san,
Thank you so your reply.
I'm looking forward to next update.

**Comment by DawnmarieDesJardins** [comment]
Closing PR - workshop is being archived.

**Pull request closed without merging**
